-- Consulta FINAL corregida para ventas de BOLITO LISTON NEGRO NUM5 en septiembre 2025
-- Esta consulta usa ÚNICAMENTE TIPO_DOCTO = 'V' sin filtros adicionales

SELECT
    pvd.ARTICULO_ID,
    a.NOMBRE AS ARTICULO,
    COUNT(DISTINCT pv.DOCTO_PV_ID) AS TOTAL_DOCUMENTOS,
    SUM(pvd.UNIDADES) AS UNIDADES_VENDIDAS,
    SUM(pvd.PRECIO_TOTAL_NETO) AS IMPORTE_TOTAL
FROM DOCTOS_PV pv
INNER JOIN DOCTOS_PV_DET pvd ON pvd.DOCTO_PV_ID = pv.DOCTO_PV_ID
INNER JOIN ARTICULOS a ON a.ARTICULO_ID = pvd.ARTICULO_ID
WHERE pv.FECHA >= DATE '2025-09-01'
    AND pv.FECHA < DATE '2025-10-01'
    AND pv.TIPO_DOCTO = 'V'  -- ← ÚNICO filtro requerido para documentos de venta
    AND pvd.UNIDADES > 0
    AND pvd.PRECIO_TOTAL_NETO > 0
    AND a.NOMBRE = 'BOLITO LISTON NEGRO NUM5'
GROUP BY pvd.ARTICULO_ID, a.NOMBRE;
